### ISSUE TITLE
Uglify error details not printing

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs#83]
When an error happens in Uglify (switch a `var` to a `let` in main.js), you get this output:

```
[BS] Proxying: http://www.bubs.dev
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.228:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.228:3001
 --------------------------------------
[BS] Reloading Browsers...
[16:22:21] Starting 'scripts'...
[16:22:22] gulp-notify: [Compile Error] unable to minify JavaScript

events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Sites/healthcarevoter.dev/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/Sites/healthcarevoter.dev/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/Sites/healthcarevoter.dev/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/Sites/healthcarevoter.dev/node_modules/gulp-uglify/minifier.js:76:19)
    at DestroyableTransform.Transform._read (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Readable.ondata (_stream_readable.js:555:20)
```

I can get Uglify to print an error when I change the handleErrors function to include a console.log:

```
var handleErrors = function() {
    var args = Array.prototype.slice.call(arguments);

    console.log( args )

    $.notify.onError({
        title: 'Compile Error',
        message: '<%= error.message %>'
    }).apply(this, args);

    if ( isProduction ) {
        // Tell Travis to Stop Bro
        process.exit(1);
    }

    this.emit('end');
};
```

Then I get this output:

```
[BS] Proxying: http://www.bubs.dev
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.228:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.228:3001
 --------------------------------------
[16:24:31] Starting 'scripts'...
[ { GulpUglifyError: unable to minify JavaScript
      at createError (/Sites/healthcarevoter.dev/node_modules/gulp-uglify/lib/create-error.js:6:14)
      at wrapper (/Sites/healthcarevoter.dev/node_modules/lodash/_createHybrid.js:87:15)
      at trycatch (/Sites/healthcarevoter.dev/node_modules/gulp-uglify/minifier.js:26:12)
      at DestroyableTransform.minify [as _transform] (/Sites/healthcarevoter.dev/node_modules/gulp-uglify/minifier.js:76:19)
      at DestroyableTransform.Transform._read (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_transform.js:159:10)
      at DestroyableTransform.Transform._write (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_transform.js:147:83)
      at doWrite (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_writable.js:347:64)
      at writeOrBuffer (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_writable.js:336:5)
      at DestroyableTransform.Writable.write (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_writable.js:274:11)
      at Readable.ondata (_stream_readable.js:555:20)
    cause: 
     JS_Parse_Error {
       message: 'SyntaxError: Unexpected token: name (timeoutDuration)',
       filename: 'js/popper.js',
       line: 27,
       col: 4,
       pos: 1419,
       stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at semicolon (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2128:56)\n    at simple_statement (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2319:73)\n    at eval (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2188:19)\n    at eval (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)\n    at eval (eval at <anonymous> (/Sites/healthcarevoter.dev/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2909:23)' },
    plugin: 'gulp-uglify',
    fileName: '/Sites/healthcarevoter.dev/wp-content/themes/timber/views/js/popper.js',
    showStack: false } ]
[16:24:32] gulp-notify: [Compile Error] unable to minify JavaScript

events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Sites/healthcarevoter.dev/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/Sites/healthcarevoter.dev/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/Sites/healthcarevoter.dev/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/Sites/healthcarevoter.dev/node_modules/gulp-uglify/minifier.js:76:19)
    at DestroyableTransform.Transform._read (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/Sites/healthcarevoter.dev/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Readable.ondata (_stream_readable.js:555:20)
```

I don't think `$.notify.onError({` is working - we should find a way to print errors in `handleErrors` that doesn't crash the gulp process.

**Comment by ccorda** [comment]
@kylehotchkiss i fixed all this, only to realize that we don't really need uglify running everytime we change JS anyways.

I did upgrade the error message handling and all gulp plugins anyways, and should we want uglify on script change, we have it.
